### ISSUE TITLE
Submit

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabE-Team1#16]
Zip all files together and upload them for submission. Include the driver programs and interface files in your zip file, even though these files were not edited.

**Comment by jillHuang7** [comment]
Zipped all files, and submitted!

**Comment by karlnicholas** [comment]
Cool. I wanted to point out that using GIT you can create a "tag" and then push the tag to the remote (GitHub here).  Once you push tag then you can create a "release", as done here, which will have everything zipped up for you. Neat way to use GitHub to tag a specific version as the one submitted as well as create the zip file for you.

**Comment by jillHuang7** [comment]
Nice! I just want to ask how can I do it!
So it is like: 
$: git tag
$: git push
$: git release
Is it?

**Comment by karlnicholas** [comment]
git tag <tagname>
git push origin <tag>

After you push the tag you will find a new release candidate on github under the releases tab. You release it from there.
