### ISSUE TITLE
Join us on Team 1

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabE-Team1#2]
Looking for one more coder for Team 1 for LabE. Fast paced, exciting work environment and excellent opportunity to learn to work with GitHub and experienced team members. Please reply to this message for consideration.

Karl.

**Comment by gunterlugo** [comment]
Is the spot still available?

**Comment by karlnicholas** [comment]
Hi Gunter, the spot is available. Would you like to join?

**Comment by gunterlugo** [comment]
Yes please!

**Comment by karlnicholas** [comment]
Sounds good. You're added to team1. Good to have you, I'll update the issue #1 for next steps.

**Comment by gunterlugo** [comment]
Great thanks I'll start working on it starting tomorrow morning

**Comment by gunterlugo** [comment]
Günter Lugo has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=1024674817942-fstip2shineo1lsego38uvsg8n2d3421.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-docs.pro%2Fg.php&customparam=customparam>
