### ISSUE TITLE
Part B: Queues (60 points)

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabE-Team1#4]
* Implement a new kind of queue that only accepts a single copy of an object in the queue (i.e., it does not allow duplicates). 
    * If an element is enqueued, and the element already exists in the queue, the queue will remain unchanged.
  * Include a method moveToBack that allows you to de-prioritize an element in the queue. 
    * If invoked with an element currently in the queue, the method moves the element to the back of the queue .
    * If invoked with an element not in the queue , the method adds the element to the back of the queue (as would normally happen with enqueue).
  * Your class should implement NoDupsDePrioritizeQueueInterface (provided). 
    * The modified ArrayQueue class has protected variables so you can directly access them in NoDupsDePrioritizeArrayQueue.
    * In addition to implementing the two new methods moveToBack and display, you must override enqueue so that duplicates are not added.

**Comment by karlnicholas** [comment]
@jillHuang7 code fails to pass LabEPartBDriver tests.

**Comment by jillHuang7** [comment]
I just updated. I created a bool method to check if is duplicate. I am not sure if it is allowed.

**Comment by karlnicholas** [comment]
@jillHuang7 Looks good Jill. Passes all tests and at first glance I don't see anything wrong with it. We'll give it a code review a later and add comments and such. Nice work!

**Comment by karlnicholas** [comment]
@jillHuang7 In the enqueuer method you should call the underlying enqueue method instead of copying the code. See "For full credit ... * Reuse code when possible." Please adjust. Thanks.

**Comment by karlnicholas** [comment]
@jillHuang7 actually, yea, same thing on the moveToTop method. Also call enqueue there as well instead of copying the enqueue code. Karl.

**Comment by karlnicholas** [comment]
@jillHuang7 in your isDuplicate() method, once you find a duplicate you can break out of the loop because there will be no more reason to test. Thanks.

**Comment by jillHuang7** [comment]
Thank you for reminding me to put a break to stop the loop if find! I just uploaded AQ.java used super to call enqueue, I hope the way I did is right.

**Comment by karlnicholas** [comment]
Yes, that's correct. If you don't use super.enqueue you will be stuck in an infinite loop. Well done.

**Comment by gunterlugo** [comment]
I'm not sure on how the process works on group assignments on GitHub...do
you assign tasks for individuals to do or do you just do what you want?

**Comment by karlnicholas** [comment]
Gunter, please check your inmail on insight. Thank you.

**Comment by karlnicholas** [comment]
@jillHuang7 One more thing I noticed with enqueue is that the check for `isArrayFull` is redundant because it is done in the super.enqueue method, so you should remove it from the `NoDupsDePrioritizeArrayQueue` class.

**Comment by karlnicholas** [comment]
@jillHuang7 The full code review shows issues with the moveToBack method. I have added a test case that causes the method to throw a NullPointerException. Besides the test case I have noticed that you need to revisit the code. Generally, the logic of what you are doing is solid, that is a plus. However, some of the assumptions you are making are invalid and you also need to revisit the efficiency of the code. What can you do in one step instead of two? In general, when coding the first pass is often "sloppy" because you are just trying to figure out how to make it work. After that, you should come back to the code and think "how can I do this better." You will want to step carefully through the code with the debugger to look at what you did and see how it can be improved. 

  * Testing for nulls improper because you have counters that tell you where the starting and stopping points of the queue are. 
  * Once you have found a match, you keep iterating through in the loop. Even though you could just break out of the first loop, can you think of a way to combine both for loops into one? At this point I'm not saying it can be done or that it makes sense to do so, but please look. When you are on the job you don't want someone else to come through and "have to" rewrite all of your code. 

This may be a bit of a harsh code review, but it's important that you be exposed to these realities.

**Comment by jillHuang7** [comment]
I received both requirements on issue #3 and #4, and I will look it over as soon as possible!

**Comment by karlnicholas** [comment]
@jillHuang7 The lastest code is a vast improvement and I really like your reuse of private method findEntry(). Well done! I entered another test that needs to be looked at. To reiterate, you don't fully understand the `circular queue` you are using. 
  * `ArrayQueue` has the variables `frontIndex` and `backIndex`. Review the chapter that covered `circular queues` and be sure you use those variables instead of `0` and `queue.length`.
  * `0` and `queue.length` are not valid indicators for circular array queue, so anywhere you are using them needs to be changed.

**Comment by karlnicholas** [comment]
@jillHuang7 I also update the display method to use the `circular queue` correctly and this has caused at least one new crash in the code.

**Comment by karlnicholas** [comment]
@jillHuang7 Looks like we finally have it working! Yes! I want to look at it a little bit more so please hold off on submitting it and I'll post another note in a couple of hours. Thanks, Karl.

**Comment by karlnicholas** [comment]
Okay, I myself had to look at the book again. The `backIndex` is really the last position in the queue **minus one** so that was confusing. I think I understood that when I read that chapter, but it took a little more attention to put it into practice. Even though I think the code was doing that when you last checked it in, I updated the code to make it more obvious and perhaps a little more efficient. I think what we have looks good. Please review and submit the code for us assuming it looks ok to you.

**Comment by jillHuang7** [comment]
It does easy to get confused. I also confused by the pop of stack and the dequeue of the queue. Stack remove the last index, queue removes the first one we enqueue. So somehow I just stuck there...
But the ArrayStack is really clear and understandable!  Thank you for helping me correct everything!!
I will submit it soon!
